version: "3.9"

networks:
  lumen_gredirect:
    driver: bridge

services:
  app:
    container_name: gredirect_php
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - lumen_gredirect

  nginx:
    container_name: gredirect_nginx
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lumen_gredirect

  db:
    container_name: gredirect_mysql5.7
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: lumen_gredirect_api
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./.docker/mysql.cnf:/etc/mysql/my.cnf
    ports:
      - 33066:3306
    networks:
      - lumen_gredirect

  phpmyadmin:
    container_name: gredirect_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9002:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - lumen_gredirect
